### ISSUE TITLE
Properly encode CSV log file

### ISSUE THREAD

**Issue by dgnorton** [dgnorton/norobo#10]
Currently, `norobod` uses `fmt.Sprintf` to build CSV call log entries. Convert it to use `encoding/csv` so that it properly quotes the fields. Also convert code that reads the log file to use the `csv` decoder.

**Comment by ndedic** [comment]
Hi,
is there a way to build/run it without "/dev/ttyACM0" (i.e. mock it somehow)?

**Comment by dgnorton** [comment]
@ndedic There is a hacky little modem simulator I wrote in this repo ([here](https://github.com/dgnorton/norobo/tree/master/cmd/modem)) and you can use `socat` to create a pair of virtual serial ports that are linked. A description of how to set it up is [here](https://github.com/dgnorton/norobo#dev-notes) in the README. Let me know if that doesn't help and I'll try to explain better.

**Comment by ndedic** [comment]
Ok, that worked, so I added "/dev/pts/23" to connstr but got "no command echo" when trying to run norobod

Edit: because it requires a command :-)... all good now

**Comment by dgnorton** [comment]
closed by #12
